name: Job Application Tracker

on:
  schedule:
    # Runs every 2 days at 9:00 AM UTC
    - cron: '0 9 */2 * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-job-tracker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests gspread google-auth google-generativeai googlesearch-python
        
    - name: Run job tracker script
      env:
        GITHUB_PAT: ${{secrets.PAT}}
        GOOGLE_API_KEY: ${{secrets.GOOGLE_API}}
        HUNTER: ${{secrets.HUNTER}}
        PATH_CREDENTIALS: ${{secrets.PATH_CREDENTIALS}}
      run: |
        echo '${{ secrets.SERVICE_ACCOUNT }}' > credentials.json
        python github.py
